### ISSUE TITLE
disconnect() API not working

### ISSUE THREAD

**Issue by sinabakh** [karyfoundation/graph#21]
API's `disconnect()` is broken.
It is [BUB](https://github.com/karyfoundation/graph/issues/17) for sure.

More investigation is required.

**Comment by sinabakh** [comment]
Ok it seems the problem is Abstraction Layer `GetDotByDotOrId` is returning wrong dots.

**Comment by sinabakh** [comment]
It seem the problem was something else
Here is the code of `DisconnectFrom`:

```
                public DisconnectFrom( dot: Dot ): boolean {
                    if ( this.Inputs[ dot.Id ] != undefined ) {
                        this.DisconnectInput( dot.Id );
                        return true;
                    } else if ( this.Outputs[ dot.Id ] != undefined ) {
                        this.DisconnectOutput( dot.Id );
                        return true;
                    }
                    return false;
                }
```

the `Inputs` and `Outputs` are arrays not dictionaries so the can be checked like that.

If we want to check the existence of a key in these arrays we should use something like this:

```
this.Inputs.includes(dot.Id)
```

**Comment by pouyakary** [comment]
That is interesting...
