### ISSUE TITLE
Dot GetNeighbors is slow

### ISSUE THREAD

**Issue by sinabakh** [karyfoundation/graph#26]
Dot's Current `GetNeighbors` algorithm is somehow slow.
It checks all `Inputs` and `Outputs` of ALL nodes.
It seems it can be so much optimized.

**Comment by sinabakh** [comment]
@pmkary @DeerMichel Do you agree on that ?
Or is there an specific reason for that kind of implementation ?

**Comment by pouyakary** [comment]
@sinabakh I'm searching for good implementations soon
